### PR TITLE
adding Dreamy's intro

### PR DESCRIPTION
**Pull request by Dreamy26**

### CODE REVIEW

**Comment by Raksha1906** [comment]
Hey, it looks great. But please don't edit the sample introduction. Add another file similar to it,

**Comment by Dreamy26** [comment]
Hello thank you! Would you like for me to delete and start over?  How can correct?

**Comment by Raksha1906** [comment]
Yeah, plz close this Pr and make a new one from a branch other than main.

**Comment by Raksha1906** [comment]
Great work!

**Pull request merged**
