### PR TITLE
Added CLI Quotes Project

### PR DESCRIPTION
**Pull request by GregSithole**

### CODE REVIEW

**Comment by Raksha1906** [comment]
Plz add the first gitignore file in yr sub folder inside projects folder only. Also, It contains license too. So, is it taken from web?

**Comment by GregSithole** [comment]
Okay, will remove that .gitignore. Sorry I added it because my IDE was adding files to the main repo. 

Nope, the license that I added is the default MIT license that any repo has, I added the License since it's basically a mini NPM project.

**Comment by GregSithole** [comment]
@Raksha1906 Okay I've removed the `.gitignore`. Let me know if there's any other change you would like.

**Comment by Raksha1906** [comment]
Okay, Perfect!

**Pull request merged**
