### PR TITLE
Added my Hello World

### PR DESCRIPTION
**Pull request by GzinSocker**
● Adding my Hello World page.
● Adding my small intro.

### CODE REVIEW

**Comment by Raksha1906** [comment]
Hey, It shows 2 files changed. Plz delete one.

**Comment by GzinSocker** [comment]
Okay!

**Comment by Raksha1906** [comment]
The file shows EOF. Plz edit the file and enter a new blank line. Then, we are good to go!

**Comment by GzinSocker** [comment]
Sure!

**Pull request merged**
